"""Initial clean migration

Revision ID: 25a8ebad0e46
Revises: 
Create Date: 2025-07-13 16:55:15.418881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25a8ebad0e46'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snapshot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Snapshot_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snapshot', schema=None) as batch_op:
        batch_op.drop_column('Snapshot_name')

    # ### end Alembic commands ###
