name: Deploy flask backend to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
        

        if [ ! -d "~/smart_cash" ]; then
          git clone https://github.com/samara5818/Backend_Flask.git
        fi
         
        cd Backend_Flask

        git fetch origin main
        git reset --hard origin/main

        if [ ! -d "venv" ]; then
          python3 -m venv venv
        fi
        source venv/bin/activate
        
        pip install --upgrade pip
        pip install -r requirements.txt

        pkill -f gunicorn || true
        
        nohup venv/bin/gunicorn -b 0.0.0.0:5000 app:app > gunicorn.log 2>&1 &
        EOF
